version: '2'
services:
  odoo_docker_server:
    image: crazyguo/odoo:v1
    command: start
    ports:
      - 8069:8069
    volumes:
      - ./volumes/odoo/addons:/opt/odoo/additional_addons
      - ./volumes/odoo/filestore:/opt/odoo/data/filestore
      - ./volumes/odoo/sessions:/opt/odoo/data/sessions
      - ./volumes/odoo/odoo.conf:/opt/odoo/etc/odoo.conf
    environment:
      - TARGET_UID=1000
