version: '2'
services:
  odoo_docker_server:
    image: div_odoo_image:prod_v6
    command: start
    ports:
      - 8070:8069
    volumes:
      - ./volumes/odoo/addons:/opt/odoo/additional_addons
      - ./volumes/odoo/filestore:/opt/odoo/data/filestore
      - ./volumes/odoo/sessions:/opt/odoo/data/sessions
      - ./volumes/odoo/odoo.conf:/opt/odoo/etc/odoo.conf
    environment:
      - TARGET_UID=1000
